### ISSUE TITLE
"Unable to set GraphQL payload data."

### ISSUE THREAD

**Issue by dstndstn** [sdss/sdss_install#21]
Hi,

Following the instructions at https://www.sdss.org/dr15/software/products under "sdss_install", line for line, I get:

```
$ ./github/sdss_install/master/bin/sdss_install_bootstrap
sdssinstall - ERROR - Unable to set GraphQL payload data.
data = None.
sdssinstall - ERROR - Unable to set_tag_edges_and_page_info
Traceback (most recent call last):
  File "/home/dstn/software/sdss/github/sdss_install/master/bin/sdss_install", line 17, in <module>
    install.set_ready()
  File "/home/dstn/software/sdss/github/sdss_install/master/python/sdss_install/install/Install.py", line 136, in set_ready
    if self.install5: self.install5.set_ready()
  File "/home/dstn/software/sdss/github/sdss_install/master/python/sdss_install/install5/Install5.py", line 71, in set_ready
    tag_names = tags.get_tag_names()
  File "/home/dstn/software/sdss/github/sdss_install/master/python/sdss_install/install5/Tags.py", line 39, in get_tag_names
    self.set_tags()
  File "/home/dstn/software/sdss/github/sdss_install/master/python/sdss_install/install5/Tags.py", line 57, in set_tags
    if self.page_info['hasNextPage']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I am getting this on a production Compute Canada machine (graham), as well as an attempted clean Docker build.

**Comment by dstndstn** [comment]
PS, is this related to the SDSS_GITHUB_KEY issue?

**Comment by dstndstn** [comment]
Because:

```
$ unset SDSS_GITHUB_KEY
$ ./github/sdss_install/master/bin/sdss_install_bootstrap
sdssinstall - ERROR - Unable to authorize the GrqphQL client using the key 'SDSS_GITHUB_KEY'.
sdssinstall - ERROR - Unable to set client data.
method = <function post at 0x2b41f17935f0>
endpoint = 'https://api.github.com/graphql'
authorization = None
sdssinstall - ERROR - Unable to set GraphQL payload data.
data = None.
```

**Comment by joelbrownstein** [comment]
Hi @nbmurphy, Can you please identify this issue with the fragility of SDSS_GITHUB_KEY, and let me know how you want to go about fixing it?

**Comment by nbmurphy** [comment]
I've been able to recreate the error on my machine. I'm working on a solution now.

**Comment by nbmurphy** [comment]
I made a significant update to sdss_install in order to fix fragile code and issued pull request #22 with @joelbrownstein as a reviewer.

**Comment by nbmurphy** [comment]
@dstndstn, as you mentioned in your comment above, I do believe that the appearence of this issue was related to the `SDSS_GITHUB_KEY` issue.  In order to avoid users of sdss_install accidentally committing, hence revoking, the GitHub token associated with step 6 of [the sdss_install bootstrap instructions](https://www.sdss.org/dr15/software/products) @joelbrownstein and I have decided to replace step 6 with the following.

6. Set SDSS GitHub read-only access token:
    a. Follow the tutorial [here](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line) to create a read-only personal access token.
    In step 7 of the tutorial select the following scope/permission: *repo:status (Access commit status)*
    b. Export the token to the environmental variable `SDSS_INSTALL_GITHUB_KEY`
for bash: 
`export SDSS_INSTALL_GITHUB_KEY=YOUR_PERSONAL_ACCESS_TOKEN_HERE`
for csh: 
`setenv SDSS_INSTALL_GITHUB_KEY YOUR_PERSONAL_ACCESS_TOKEN_HERE`

**Comment by dstndstn** [comment]
Okay, thanks.  I don't really understand why you need a token to check out code from the command line, but ok.

**Comment by joelbrownstein** [comment]
Hmm, I actually also think using github api is overkill, just to ping github to see if the repo and branch exist.

@nbmurphy , can't you simplify the logic to just do something like a python subprocess to 

`$ git ls-remote --heads git@github.com:sdss/sdss_install.git nbmurphy
ac4a333859f35d562cffd2a4c74a91b0752ae97f	refs/heads/nbmurphy`

which returns a result (because sdss_install exists as a repo and nbmurphy exists as a branch)?

vs. 

`$ git ls-remote --heads git@github.com:sdss/sdss_install.git XXX`

which returns nothing (because XXX is nonexistent).

This would greatly simplify the code, and be much less fragile than using the github graphql for such a simple thing as check existence.

**Comment by nbmurphy** [comment]
@joelbrownstein I like that solution. I'll start implementing it. (I'll add the GraphQL Branch and Tag classes to sdss_github to retain their functionality.)

**Comment by nbmurphy** [comment]
@joelbrownstein I have removed all GraphQL related code and added the `git ls-remote` related code suggested above. I have a pending pull request awaiting your approval, which will close this issue (since GraphQL is now absent from sdss_install). In order to fully test sdss_install_bootstrap functionality, the pull request needs to be merged to master, but it seems to be working using local testing.
