### ISSUE TITLE
sdss_install_bootstrap (Install5.py) uses a git URL that requires SSH login

### ISSUE THREAD

**Issue by dstndstn** [sdss/sdss_install#46]
Here,
https://github.com/sdss/sdss_install/blob/master/python/sdss_install/install5/Install5.py#L235
you're using a "git@github.com" URL, which requires (a) ssh to be installed; and (b) the user to have a github account with ssh key.

I hope this wasn't intentional, because it makes it much more difficult to install in scripted environments (eg the Docker container I'm building).  An https:// github URL would work better, wouldn't it?

ie change
```
                github_url = github_url if github_url else 'git@github.com:sdss'
```
to
```
                github_url = github_url if github_url else 'https://github.com/sdss'
```

**Comment by joelbrownstein** [comment]
Hi Dustin,

Many of the products in SDSS GitHub are currently private to the SDSS collaboration (but some are already public), so we need the GitHub clone over SSH for our purposes (i.e it was intentional!).

However, we appreciate that there are other use cases, so we can make a branch for this feature, whereby a keyword can be supplied to switch the behaviour from over ssh to over https.

Does that work for you?

Cheers, Joel

**Comment by dstndstn** [comment]
I guess so... it's just... sdss_install_bootstrap should be installable without credentials, right?, since it is required to install all the other public code.

**Comment by nbmurphy** [comment]
I opened pull request #47 to address this issue.

**Comment by nbmurphy** [comment]
Hi Dustin, 

Since `sdss_install` is a public repository it should be installable without credentials. The changes I made in pull request #47 addresses this. 

Are you okay with the implementation --- discussed by @joelbrownstein above?

All the best,
Ben

**Comment by dstndstn** [comment]
You're not suggesting you want this to exist only live in a branch
permanently, are you?

**Comment by nbmurphy** [comment]
No, once I get confirmation from you and @joelbrownstein for the changes in pull request #47, we will merge the pull request to master and re-tag.
